[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."crawl-and-summarize-simple"]
  timeout = 30

[functions."api-key-simple"]
  timeout = 10

[functions."health-simple"]
  timeout = 5

[functions."regions-simple"]
  timeout = 5

[functions."saved-urls-simple"]
  timeout = 5

[[plugins]]
package = "@netlify/plugin-functions-install-core"
