[build]
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"

[[functions]]
  function = "crawl-and-summarize"
  timeout = 30
  memory = 1024

[[functions]]
  function = "api-key"
  timeout = 10
  memory = 512

[[functions]]
  function = "regions"
  timeout = 10
  memory = 512

[[functions]]
  function = "saved-urls"
  timeout = 10
  memory = 512

[[functions]]
  function = "health"
  timeout = 10
  memory = 512

[[functions]]
  function = "saved-prompt"
  timeout = 10
  memory = 512
