[build]
  publish = "frontend/dist"
  functions = "netlify/functions"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  timeout = 60
  memory = 2048
