[build]
  base = "."
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[functions]]
  function = "crawl-and-summarize"
  timeout = 30

[[functions]]
  function = "api-key"
  timeout = 10

[[functions]]
  function = "regions"
  timeout = 10

[[functions]]
  function = "saved-urls"
  timeout = 10

[[functions]]
  function = "saved-prompt"
  timeout = 10

[[functions]]
  function = "health"
  timeout = 10

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
